// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRsrrGYT5e7Y9tBhZseNMIZ3PzUWRf4tg',
    appId: '1:464440370133:web:927ac110fa0811a23f935c',
    messagingSenderId: '464440370133',
    projectId: 'chargerrr-a6b4b',
    authDomain: 'chargerrr-a6b4b.firebaseapp.com',
    storageBucket: 'chargerrr-a6b4b.firebasestorage.app',
    measurementId: 'G-XFVCFH0GNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMOaLPXwEpwAfYrbCgg2kUzKgZRYKmgBg',
    appId: '1:464440370133:android:d5356beb5374871e3f935c',
    messagingSenderId: '464440370133',
    projectId: 'chargerrr-a6b4b',
    storageBucket: 'chargerrr-a6b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MZXcOS2CO2lg2XbdA7aQmwBgviMdvGU',
    appId: '1:464440370133:ios:df0d3df22ed165b13f935c',
    messagingSenderId: '464440370133',
    projectId: 'chargerrr-a6b4b',
    storageBucket: 'chargerrr-a6b4b.firebasestorage.app',
    iosBundleId: 'com.example.chargerrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_MZXcOS2CO2lg2XbdA7aQmwBgviMdvGU',
    appId: '1:464440370133:ios:df0d3df22ed165b13f935c',
    messagingSenderId: '464440370133',
    projectId: 'chargerrr-a6b4b',
    storageBucket: 'chargerrr-a6b4b.firebasestorage.app',
    iosBundleId: 'com.example.chargerrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRsrrGYT5e7Y9tBhZseNMIZ3PzUWRf4tg',
    appId: '1:464440370133:web:bd8eea459955668e3f935c',
    messagingSenderId: '464440370133',
    projectId: 'chargerrr-a6b4b',
    authDomain: 'chargerrr-a6b4b.firebaseapp.com',
    storageBucket: 'chargerrr-a6b4b.firebasestorage.app',
    measurementId: 'G-QK4X67L0HJ',
  );
}
